namespace GameLogic.Player.Actions;

public static class ActionResult
{
	public static readonly MetaActionResult Success; //Field offset: 0x0
	public static readonly MetaActionResult InvalidDirectorEventId; //Field offset: 0x8
	public static readonly MetaActionResult NotEnoughResources; //Field offset: 0x10
	public static readonly MetaActionResult AlreadyUnlocked; //Field offset: 0x18
	public static readonly MetaActionResult InvalidCoordinate; //Field offset: 0x20
	public static readonly MetaActionResult LevelUpNotPossible; //Field offset: 0x28
	public static readonly MetaActionResult CoordinateDoesNotContainItem; //Field offset: 0x30
	public static readonly MetaActionResult CoordinateDoesNotContainWantedItem; //Field offset: 0x38
	public static readonly MetaActionResult InvalidMergeBoardId; //Field offset: 0x40
	public static readonly MetaActionResult InvalidMergeBoardInventoryId; //Field offset: 0x48
	public static readonly MetaActionResult NoHotspotDefinition; //Field offset: 0x50
	public static readonly MetaActionResult InvalidHotspot; //Field offset: 0x58
	public static readonly MetaActionResult ItemCantBeActivated; //Field offset: 0x60
	public static readonly MetaActionResult InvalidCurrentTime; //Field offset: 0x68
	public static readonly MetaActionResult InvalidEpochDay; //Field offset: 0x70
	public static readonly MetaActionResult CannotPausePausedTimer; //Field offset: 0x78
	public static readonly MetaActionResult CannotUnpauseUnpausedTimer; //Field offset: 0x80
	public static readonly MetaActionResult ShopItemsRollNotDue; //Field offset: 0x88
	public static readonly MetaActionResult StoreSetupOfferNotDue; //Field offset: 0x90
	public static readonly MetaActionResult ShopItemNotCurrentlyBeingSold; //Field offset: 0x98
	public static readonly MetaActionResult ShopItemNotInShopItemFinder; //Field offset: 0xA0
	public static readonly MetaActionResult NotEnoughCurrency; //Field offset: 0xA8
	public static readonly MetaActionResult TryingToUseNegativeCurrency; //Field offset: 0xB0
	public static readonly MetaActionResult PocketHasNoItems; //Field offset: 0xB8
	public static readonly MetaActionResult PocketItemsExceeded; //Field offset: 0xC0
	public static readonly MetaActionResult CodeAlreadyUsed; //Field offset: 0xC8
	public static readonly MetaActionResult NoFreeSpaceInInventory; //Field offset: 0xD0
	public static readonly MetaActionResult InventoryDoesNotHaveItem; //Field offset: 0xD8
	public static readonly MetaActionResult CannotMoveItemFromBoardToInventory; //Field offset: 0xE0
	public static readonly MetaActionResult CannotMoveItemFromInventoryToBoard; //Field offset: 0xE8
	public static readonly MetaActionResult CannotBuyInventorySlot; //Field offset: 0xF0
	public static readonly MetaActionResult CannotUnlockProducerInventorySlot; //Field offset: 0xF8
	public static readonly MetaActionResult CannotBuyEnergy; //Field offset: 0x100
	public static readonly MetaActionResult NoFreeSpaceOnBoard; //Field offset: 0x108
	public static readonly MetaActionResult WouldNotBeValidMerge; //Field offset: 0x110
	public static readonly MetaActionResult WouldNotBeValidMove; //Field offset: 0x118
	public static readonly MetaActionResult WouldNotBeValidSwap; //Field offset: 0x120
	public static readonly MetaActionResult WouldNotBeValidChestOpen; //Field offset: 0x128
	public static readonly MetaActionResult WouldNotBeValidChestFastOpen; //Field offset: 0x130
	public static readonly MetaActionResult WouldNotBeValidSinkIn; //Field offset: 0x138
	public static readonly MetaActionResult WouldNotBeValidConsumeIn; //Field offset: 0x140
	public static readonly MetaActionResult InvalidConversionStates; //Field offset: 0x148
	public static readonly MetaActionResult AlreadyAcceptedTOS; //Field offset: 0x150
	public static readonly MetaActionResult NothingToMakeClaimable; //Field offset: 0x158
	public static readonly MetaActionResult EventAlreadyOnGoing; //Field offset: 0x160
	public static readonly MetaActionResult EventDefinitionMissing; //Field offset: 0x168
	public static readonly MetaActionResult EventNotGoing; //Field offset: 0x170
	public static readonly MetaActionResult EventNotInCollectionMode; //Field offset: 0x178
	public static readonly MetaActionResult EventProgressDefinitionMissing; //Field offset: 0x180
	public static readonly MetaActionResult SocialRewardAlreadyClaimed; //Field offset: 0x188
	public static readonly MetaActionResult SocialRewardNoRewards; //Field offset: 0x190
	public static readonly MetaActionResult NoChangeToGameSettings; //Field offset: 0x198
	public static readonly MetaActionResult ShopOfferNotActive; //Field offset: 0x1A0
	public static readonly MetaActionResult ShopOfferNoPurchasesToClear; //Field offset: 0x1A8
	public static readonly MetaActionResult DailyTaskStillActive; //Field offset: 0x1B0
	public static readonly MetaActionResult DailyTaskInvalidSlotIndex; //Field offset: 0x1B8
	public static readonly MetaActionResult DailyTaskInputFailed; //Field offset: 0x1C0
	public static readonly MetaActionResult DailyTaskNotReadyForTotalComplete; //Field offset: 0x1C8
	public static readonly MetaActionResult DailyTaskAlreadyTotalCompleted; //Field offset: 0x1D0
	public static readonly MetaActionResult DailyTasksV2AlreadyCompleted; //Field offset: 0x1D8
	public static readonly MetaActionResult DailyTasksV2AlreadyRegistered; //Field offset: 0x1E0
	public static readonly MetaActionResult DailyTasksV2InvalidIndex; //Field offset: 0x1E8
	public static readonly MetaActionResult DailyTasksV2MissingRequirementItem; //Field offset: 0x1F0
	public static readonly MetaActionResult DailyTasksV2NotAvailable; //Field offset: 0x1F8
	public static readonly MetaActionResult DailyTasksV2StillActive; //Field offset: 0x200
	public static readonly MetaActionResult DailyTasksV2RefreshDisabled; //Field offset: 0x208
	public static readonly MetaActionResult MissingSocialAuthenticationReward; //Field offset: 0x210
	public static readonly MetaActionResult SocialAuthenticationRewardNotSet; //Field offset: 0x218
	public static readonly MetaActionResult SurveyRewardAlreadyClaimed; //Field offset: 0x220
	public static readonly MetaActionResult SurveyRewardNoRewards; //Field offset: 0x228
	public static readonly MetaActionResult SurveyResultAlreadyAdded; //Field offset: 0x230
	public static readonly MetaActionResult NegativeDecorationSlot; //Field offset: 0x238
	public static readonly MetaActionResult PlayerDoesNotOwnDecoration; //Field offset: 0x240
	public static readonly MetaActionResult ItemRequirementsNotMetFromMergeBoards; //Field offset: 0x248
	public static readonly MetaActionResult EventNotFound; //Field offset: 0x250
	public static readonly MetaActionResult ProgressionTrackNotFound; //Field offset: 0x258
	public static readonly MetaActionResult EventTaskIdNotFound; //Field offset: 0x260
	public static readonly MetaActionResult EventLevelNotFound; //Field offset: 0x268
	public static readonly MetaActionResult EventAttemptRollbackPoints; //Field offset: 0x270
	public static readonly MetaActionResult EventOfferNotFound; //Field offset: 0x278
	public static readonly MetaActionResult EventIsNotActive; //Field offset: 0x280
	public static readonly MetaActionResult UnableToAffordPrice; //Field offset: 0x288
	public static readonly MetaActionResult EventLevelNotReached; //Field offset: 0x290
	public static readonly MetaActionResult EventLevelCurrentMismatch; //Field offset: 0x298
	public static readonly MetaActionResult EventUnableToResolve; //Field offset: 0x2A0
	public static readonly MetaActionResult EventOfferSetNotFound; //Field offset: 0x2A8
	public static readonly MetaActionResult EventOfferSetNotCompleted; //Field offset: 0x2B0
	public static readonly MetaActionResult EventOfferSetAlreadyClaimed; //Field offset: 0x2B8
	public static readonly MetaActionResult PlayerDoesNotHavePrecursorEventOfferSet; //Field offset: 0x2C0
	public static readonly MetaActionResult EventOfferAlreadyConsumed; //Field offset: 0x2C8
	public static readonly MetaActionResult EventIsActive; //Field offset: 0x2D0
	public static readonly MetaActionResult UnableToFinalizeEvent; //Field offset: 0x2D8
	public static readonly MetaActionResult EventCannotBeStarted; //Field offset: 0x2E0
	public static readonly MetaActionResult EventCannotBeExtended; //Field offset: 0x2E8
	public static readonly MetaActionResult EventExtensionBeyondSafetyMargin; //Field offset: 0x2F0
	public static readonly MetaActionResult ScriptedEventNotFound; //Field offset: 0x2F8
	public static readonly MetaActionResult ItemNotDiscovered; //Field offset: 0x300
	public static readonly MetaActionResult DiscoveryRewardAlreadyClaimed; //Field offset: 0x308
	public static readonly MetaActionResult DiscoveryRewardNotSet; //Field offset: 0x310
	public static readonly MetaActionResult InvalidItemType; //Field offset: 0x318
	public static readonly MetaActionResult InvalidMergeChainId; //Field offset: 0x320
	public static readonly MetaActionResult ThirdPartySurveyNotStarted; //Field offset: 0x328
	public static readonly MetaActionResult ThirdPartySurveyAlreadyStarted; //Field offset: 0x330
	public static readonly MetaActionResult ThirdPartySurveyAlreadyCompleted; //Field offset: 0x338
	public static readonly MetaActionResult BankFull; //Field offset: 0x340
	public static readonly MetaActionResult GameFeatureDisabled; //Field offset: 0x348
	public static readonly MetaActionResult GarageCleanupLevelAlreadyStarted; //Field offset: 0x350
	public static readonly MetaActionResult GarageCleanupLevelNotStarted; //Field offset: 0x358
	public static readonly MetaActionResult GarageCleanupInvalidLevel; //Field offset: 0x360
	public static readonly MetaActionResult GarageCleanupBoardNotFilled; //Field offset: 0x368
	public static readonly MetaActionResult GarageCleanupInvalidSlotCoordinate; //Field offset: 0x370
	public static readonly MetaActionResult GarageCleanupSlotAlreadyFilled; //Field offset: 0x378
	public static readonly MetaActionResult GarageCleanupItemRequirementNotMet; //Field offset: 0x380
	public static readonly MetaActionResult GarageCleanupSpawnerItemAlreadyClaimed; //Field offset: 0x388
	public static readonly MetaActionResult GarageCleanupLevelAlreadyBought; //Field offset: 0x390
	public static readonly MetaActionResult AreaNotFound; //Field offset: 0x398
	public static readonly MetaActionResult AreaNotCompletable; //Field offset: 0x3A0
	public static readonly MetaActionResult TeasedAreaAlreadyNoted; //Field offset: 0x3A8
	public static readonly MetaActionResult ProgressionEventModelMissing; //Field offset: 0x3B0
	public static readonly MetaActionResult ProgressionEventPremiumIAPNotAllowed; //Field offset: 0x3B8
	public static readonly MetaActionResult ProgressionEventPremiumIAPMissing; //Field offset: 0x3C0
	public static readonly MetaActionResult ProgressionEventRewardNotClaimable; //Field offset: 0x3C8
	public static readonly MetaActionResult ProgressionEventNotValidForEndDialogue; //Field offset: 0x3D0
	public static readonly MetaActionResult ProgressionEventExtraInventoryNotValidForRemove; //Field offset: 0x3D8
	public static readonly MetaActionResult FeatureNotAvailable; //Field offset: 0x3E0
	public static readonly MetaActionResult AmountExceeded; //Field offset: 0x3E8
	public static readonly MetaActionResult RequirementsNotMet; //Field offset: 0x3F0
	public static readonly MetaActionResult CurrencyBankNotPurchaseable; //Field offset: 0x3F8
	public static readonly MetaActionResult CollectibleBoardEventPortalItemAlreadyGiven; //Field offset: 0x400
	public static readonly MetaActionResult CollectibleBoardEventLevelNotClaimable; //Field offset: 0x408
	public static readonly MetaActionResult CollectibleBoardEventNotValidForEndDialogue; //Field offset: 0x410
	public static readonly MetaActionResult BoardEventNotValidForEnterBoardDialogue; //Field offset: 0x418
	public static readonly MetaActionResult PlayerNameNotSet; //Field offset: 0x420
	public static readonly MetaActionResult LeaderboardEventLevelNotClaimable; //Field offset: 0x428
	public static readonly MetaActionResult LeaderboardEventRankingRewardsNotClaimable; //Field offset: 0x430
	public static readonly MetaActionResult PlayerBannedFromLeaderboards; //Field offset: 0x438
	public static readonly MetaActionResult LeaderboardEventNotValidForEndDialogue; //Field offset: 0x440
	public static readonly MetaActionResult LeaderboardEventAlreadySetup; //Field offset: 0x448
	public static readonly MetaActionResult LeaderboardEventAlreadyJoined; //Field offset: 0x450
	public static readonly MetaActionResult BoardEventPortalItemAlreadyGiven; //Field offset: 0x458
	public static readonly MetaActionResult SideBoardEventPortalItemAlreadyGiven; //Field offset: 0x460
	public static readonly MetaActionResult SideBoardEventLevelNotClaimable; //Field offset: 0x468
	public static readonly MetaActionResult CannotSellItemFromBoard; //Field offset: 0x470
	public static readonly MetaActionResult PhotoOfItemAlreadyTaken; //Field offset: 0x478
	public static readonly MetaActionResult UnclaimedWorldRecordFishRewardNotFound; //Field offset: 0x480
	public static readonly MetaActionResult WeightStarRewardAlreadyClaimed; //Field offset: 0x488
	public static readonly MetaActionResult WeightStarWeightNotReached; //Field offset: 0x490
	public static readonly MetaActionResult NoSeasonDefinition; //Field offset: 0x498
	public static readonly MetaActionResult CyclesAlreadyFull; //Field offset: 0x4A0
	public static readonly MetaActionResult RentableInventoryIsNull; //Field offset: 0x4A8
	public static readonly MetaActionResult RentableInventoryMaximumBought; //Field offset: 0x4B0
	public static readonly MetaActionResult RentableInventorySettingsNull; //Field offset: 0x4B8
	public static readonly MetaActionResult SongAlreadyUnlocked; //Field offset: 0x4C0
	public static readonly MetaActionResult InvalidSideBoardEventCharacter; //Field offset: 0x4C8
	public static readonly MetaActionResult NoSideBoardEventCharacterToNote; //Field offset: 0x4D0
	public static readonly MetaActionResult IncorrectSideBoardEventCharacterToNote; //Field offset: 0x4D8
	public static readonly MetaActionResult InvalidDecorationShopItemId; //Field offset: 0x4E0
	public static readonly MetaActionResult InvalidDecorationShopItemCostIndex; //Field offset: 0x4E8
	public static readonly MetaActionResult InvalidPlayerMode; //Field offset: 0x4F0
	public static readonly MetaActionResult InfiniteEnergyBlocksPlayerMode; //Field offset: 0x4F8
	public static readonly MetaActionResult LevelEventLevelNotClaimable; //Field offset: 0x500
	public static readonly MetaActionResult CollectableCannotBeCollected; //Field offset: 0x508
	public static readonly MetaActionResult AdWatchNotSuccessful; //Field offset: 0x510
	public static readonly MetaActionResult InvalidPetId; //Field offset: 0x518
	public static readonly MetaActionResult PlayerDoesNotOwnPet; //Field offset: 0x520
	public static readonly MetaActionResult WebShopPurchaseAlreadyExists; //Field offset: 0x528
	public static readonly MetaActionResult InvalidWebShopPurchaseId; //Field offset: 0x530
	public static readonly MetaActionResult InvalidOfferGroupForActivation; //Field offset: 0x538
	public static readonly MetaActionResult MysteryMachineEventBoardAlreadySetup; //Field offset: 0x540
	public static readonly MetaActionResult InvalidMysteryMachine; //Field offset: 0x548
	public static readonly MetaActionResult MysteryMachineContainerFull; //Field offset: 0x550
	public static readonly MetaActionResult MysteryMachineOverheat; //Field offset: 0x558
	public static readonly MetaActionResult MysteryMachineHasMerges; //Field offset: 0x560
	public static readonly MetaActionResult MysteryMachineHasNoMerges; //Field offset: 0x568
	public static readonly MetaActionResult MysteryMachineNoCameraTargets; //Field offset: 0x570
	public static readonly MetaActionResult MysteryMachinePreparationError; //Field offset: 0x578
	public static readonly MetaActionResult MysteryMachineCannotClaimAllTasksCompletedReward; //Field offset: 0x580
	public static readonly MetaActionResult MysteryMachineSpecialSaleMaxPurchaseCountReached; //Field offset: 0x588
	public static readonly MetaActionResult MysteryMachineSpawnItemsQueueEmpty; //Field offset: 0x590
	public static readonly MetaActionResult MysteryMachineSpawnItemsQueueNotEmpty; //Field offset: 0x598
	public static readonly MetaActionResult AdsAlreadySet; //Field offset: 0x5A0
	public static readonly MetaActionResult AdvertisementPlacementIdDoesntMatch; //Field offset: 0x5A8
	public static readonly MetaActionResult BoultonLeagueEventDivisionAlreadyJoined; //Field offset: 0x5B0
	public static readonly MetaActionResult BoultonLeagueEventLeaderboardPlacementRewardsNotClaimable; //Field offset: 0x5B8
	public static readonly MetaActionResult BoultonLeagueEventPlayerBanned; //Field offset: 0x5C0
	public static readonly MetaActionResult BoultonLeagueEventStageMissing; //Field offset: 0x5C8
	public static readonly MetaActionResult MakeYourOwnOfferItemsNotSelected; //Field offset: 0x5D0
	public static readonly MetaActionResult ScriptedEventCannotBeStarted; //Field offset: 0x5D8
	public static readonly MetaActionResult MysteryMachineEventNotUsingLeaderboard; //Field offset: 0x5E0
	public static readonly MetaActionResult NoMysteryMachineLeaderboardRewardsToClaim; //Field offset: 0x5E8
	public static readonly MetaActionResult MysteryMachineLeaderboardPositionAlreadySet; //Field offset: 0x5F0
	public static readonly MetaActionResult MysteryMachineLeaderboardScoreOutOfRange; //Field offset: 0x5F8
	public static readonly MetaActionResult NoAdRewardToClaim; //Field offset: 0x600
	public static readonly MetaActionResult AdRewardActionFailed; //Field offset: 0x608
	public static readonly MetaActionResult AdvertisementPlacementNotFound; //Field offset: 0x610
	public static readonly MetaActionResult CannotForceResetFlashSale; //Field offset: 0x618
	public static readonly MetaActionResult MissingEnergyType; //Field offset: 0x620
	public static readonly MetaActionResult CannotBuyEvidenceBox; //Field offset: 0x628
	public static readonly MetaActionResult CannotCraftCard; //Field offset: 0x630
	public static readonly MetaActionResult CannotGetSkipTimePriceForEvidenceBox; //Field offset: 0x638
	public static readonly MetaActionResult NoResetNeeded; //Field offset: 0x640
	public static readonly MetaActionResult RewardAlreadyClaimed; //Field offset: 0x648
	public static readonly MetaActionResult MinigameNotFound; //Field offset: 0x650
	public static readonly MetaActionResult ShortLeaderboardEventLevelNotClaimable; //Field offset: 0x658
	public static readonly MetaActionResult CannotAcknowledgeShortLeaderboardEventStageEnded; //Field offset: 0x660
	public static readonly MetaActionResult CannotTriggerShortLeaderboardEventEndDialogue; //Field offset: 0x668
	public static readonly MetaActionResult CannotRequestJoinShortLeaderboardEventStage; //Field offset: 0x670
	public static readonly MetaActionResult CannotStartShortLeaderboardEventStage; //Field offset: 0x678
	public static readonly MetaActionResult CannotReplayShortLeaderboardEventStage; //Field offset: 0x680
	public static readonly MetaActionResult CannotClaimShortLeaderboardEventFinalReward; //Field offset: 0x688
	public static readonly MetaActionResult CannotMarkShortLeaderboardEventStageCompletionDialogueTriggered; //Field offset: 0x690
	public static readonly MetaActionResult CannotClaimShortLeaderboardEventStageCompletionRewards; //Field offset: 0x698
	public static readonly MetaActionResult CannotClaimShortLeaderboardEventStageStars; //Field offset: 0x6A0
	public static readonly MetaActionResult CannotEndShortLeaderboardEventStage; //Field offset: 0x6A8
	public static readonly MetaActionResult NoAvailableMuseumSlotForItem; //Field offset: 0x6B0
	public static readonly MetaActionResult AlreadyHasMuseumCollection; //Field offset: 0x6B8
	public static readonly MetaActionResult UnconfiguredMuseumShelf; //Field offset: 0x6C0
	public static readonly MetaActionResult MuseumCollectionNotFound; //Field offset: 0x6C8
	public static readonly MetaActionResult MuseumShelfNotFound; //Field offset: 0x6D0
	public static readonly MetaActionResult CannotRequestJoinClassicRacesEventStage; //Field offset: 0x6D8
	public static readonly MetaActionResult CannotReplayClassicRacesEventStage; //Field offset: 0x6E0
	public static readonly MetaActionResult CannotStartClassicRacesEventStage; //Field offset: 0x6E8
	public static readonly MetaActionResult CannotEndClassicRacesEventStage; //Field offset: 0x6F0
	public static readonly MetaActionResult CannotFinalizeClassicRacesEventStage; //Field offset: 0x6F8
	public static readonly MetaActionResult ClassicRacesEventIntroAlreadyFinished; //Field offset: 0x700
	public static readonly MetaActionResult ClassicRacesEventRaceLostDialogAlreadyFinished; //Field offset: 0x708
	public static readonly MetaActionResult ClassicRacesEventRaceWonDialogAlreadyFinished; //Field offset: 0x710
	public static readonly MetaActionResult InsufficientLevelToChangeTheBoard; //Field offset: 0x718
	public static readonly MetaActionResult InsufficientLettersToChangeTheBoard; //Field offset: 0x720
	[Obsolete("Task Group were removed")]
	public static readonly MetaActionResult TaskListNotFound; //Field offset: 0x728
	[Obsolete("Task Group were removed")]
	public static readonly MetaActionResult TaskListNotActive; //Field offset: 0x730
	[Obsolete("Task Group were removed")]
	public static readonly MetaActionResult TaskListNotActivatable; //Field offset: 0x738
	[Obsolete("Task Group were removed")]
	public static readonly MetaActionResult TaskListNotDeactivatable; //Field offset: 0x740
	[Obsolete("Task Group were removed")]
	public static readonly MetaActionResult TaskListHasNotEnoughEmptySlots; //Field offset: 0x748
	public static readonly MetaActionResult CannotGiveCoreSupportEventPortalItem; //Field offset: 0x750
	public static readonly MetaActionResult CannotInitCoreSupportEventMinigame; //Field offset: 0x758
	public static readonly MetaActionResult CannotClaimCoreSupportEventMinigameReward; //Field offset: 0x760
	public static readonly MetaActionResult InvalidRecipe; //Field offset: 0x768
	public static readonly MetaActionResult NotEnoughIngredients; //Field offset: 0x770
	public static readonly MetaActionResult NoSuchShelf; //Field offset: 0x778
	public static readonly MetaActionResult ShelfItemAlreadySeen; //Field offset: 0x780
	public static readonly MetaActionResult IneligibleToClaimReward; //Field offset: 0x788
	public static readonly MetaActionResult DigEventTileAlreadyRevealed; //Field offset: 0x790
	public static readonly MetaActionResult AreaNotUnlockable; //Field offset: 0x798
	public static readonly MetaActionResult UnlockableAreaAlreadyNoted; //Field offset: 0x7A0
	public static readonly MetaActionResult NoPendingOnFire; //Field offset: 0x7A8
	public static readonly MetaActionResult StatsObjectiveRequirementNotMet; //Field offset: 0x7B0
	public static readonly MetaActionResult StatsObjectiveLocked; //Field offset: 0x7B8
	public static readonly MetaActionResult StatsObjectiveAlreadyCompleted; //Field offset: 0x7C0
	public static readonly MetaActionResult NoRewardToClaim; //Field offset: 0x7C8
	public static readonly MetaActionResult NotEnoughWildItems; //Field offset: 0x7D0
	public static readonly MetaActionResult CouldntUseEnegy; //Field offset: 0x7D8
	public static readonly MetaActionResult ItemIsNotRequiredInAnyActiveTask; //Field offset: 0x7E0
	public static readonly MetaActionResult MergeBoardAlreadyExists; //Field offset: 0x7E8

	private static ActionResult() { }

}

