//Type is in global namespace

public static class ItemTags
{
	public static readonly string itemRoot; //Field offset: 0x0
	public static readonly string fog; //Field offset: 0x8
	public static readonly string bottle; //Field offset: 0x10
	public static readonly string fancyBlueChest; //Field offset: 0x18
	public static readonly string fancyBrownChest; //Field offset: 0x20
	public static readonly string drawer; //Field offset: 0x28
	public static readonly string flower; //Field offset: 0x30
	public static readonly string flowerpot; //Field offset: 0x38
	public static readonly string gardenBench; //Field offset: 0x40
	public static readonly string gardenGloves; //Field offset: 0x48
	public static readonly string gardenToolBarrel; //Field offset: 0x50
	public static readonly string gardenTools; //Field offset: 0x58
	public static readonly string lamp; //Field offset: 0x60
	public static readonly string locket; //Field offset: 0x68
	public static readonly string moth; //Field offset: 0x70
	public static readonly string orangeFlower; //Field offset: 0x78
	public static readonly string radio; //Field offset: 0x80
	public static readonly string scarab; //Field offset: 0x88
	public static readonly string scarabbox; //Field offset: 0x90
	public static readonly string screws; //Field offset: 0x98
	public static readonly string ship; //Field offset: 0xA0
	public static readonly string shippingcontainer; //Field offset: 0xA8
	public static readonly string shrapnel; //Field offset: 0xB0
	public static readonly string song; //Field offset: 0xB8
	public static readonly string seedBag; //Field offset: 0xC0
	public static readonly string seedBagEmpty; //Field offset: 0xC8
	public static readonly string threadball; //Field offset: 0xD0
	public static readonly string toolbox; //Field offset: 0xD8
	public static readonly string toyCar; //Field offset: 0xE0
	public static readonly string vase; //Field offset: 0xE8
	public static readonly string wood; //Field offset: 0xF0
	public static readonly string tools; //Field offset: 0xF8
	public static readonly string tree; //Field offset: 0x100
	public static readonly string silk; //Field offset: 0x108
	public static readonly string loveStory; //Field offset: 0x110
	public static readonly string butterfly; //Field offset: 0x118
	public static readonly string mosaic; //Field offset: 0x120
	public static readonly string bush; //Field offset: 0x128
	public static readonly string bushBerry; //Field offset: 0x130
	public static readonly string bushDry; //Field offset: 0x138
	public static readonly string energy; //Field offset: 0x140
	public static readonly string secondaryEnergy; //Field offset: 0x148
	public static readonly string stoneCan; //Field offset: 0x150
	public static readonly string cleaning; //Field offset: 0x158
	public static readonly string broomCabinet; //Field offset: 0x160
	public static readonly string paintCan; //Field offset: 0x168
	public static readonly string piggyBank; //Field offset: 0x170
	public static readonly string houseplant; //Field offset: 0x178
	public static readonly string brownChest; //Field offset: 0x180
	public static readonly string plantedBush; //Field offset: 0x188
	public static readonly string simpleBrownBox; //Field offset: 0x190
	public static readonly string clothCoveredBrownBox; //Field offset: 0x198
	public static readonly string goldRoot; //Field offset: 0x1A0
	public static readonly string bronzeCoin; //Field offset: 0x1A8
	public static readonly string silverCoin; //Field offset: 0x1B0
	public static readonly string goldCoin; //Field offset: 0x1B8
	public static readonly string energyBox; //Field offset: 0x1C0
	public static readonly string bronzeCoinBox; //Field offset: 0x1C8
	public static readonly string redBox; //Field offset: 0x1D0
	public static readonly string blueBox; //Field offset: 0x1D8
	public static readonly string thread; //Field offset: 0x1E0
	public static readonly string detergent; //Field offset: 0x1E8
	public static readonly string diamond; //Field offset: 0x1F0
	public static readonly string booster; //Field offset: 0x1F8
	public static readonly string boosterActivated; //Field offset: 0x200
	public static readonly string timeSkipBooster; //Field offset: 0x208
	public static readonly string boosterShard; //Field offset: 0x210
	public static readonly string timeSkipBoosterShard; //Field offset: 0x218
	public static readonly string carHoodOrnament; //Field offset: 0x220
	public static readonly string woodenChest; //Field offset: 0x228
	public static readonly string blueChest; //Field offset: 0x230
	public static readonly string redChest; //Field offset: 0x238
	public static readonly string bag; //Field offset: 0x240
	public static readonly string orangeJuice; //Field offset: 0x248
	public static readonly string jewellery; //Field offset: 0x250
	public static readonly string clock; //Field offset: 0x258
	public static readonly string billiardBalls; //Field offset: 0x260
	public static readonly string cueBall; //Field offset: 0x268
	public static readonly string billiardBallContainer; //Field offset: 0x270
	public static readonly string apple; //Field offset: 0x278
	public static readonly string levelUpBooster; //Field offset: 0x280
	public static readonly string presentWhite; //Field offset: 0x288
	public static readonly string presentWhiteRound; //Field offset: 0x290
	public static readonly string presentGolden; //Field offset: 0x298
	public static readonly string presentBlue; //Field offset: 0x2A0
	public static readonly string piggyBankProgress; //Field offset: 0x2A8
	public static readonly string hotelStay; //Field offset: 0x2B0
	public static readonly string scyscraper; //Field offset: 0x2B8
	public static readonly string lindsayDay; //Field offset: 0x2C0
	public static readonly string shoes; //Field offset: 0x2C8
	public static readonly string eventProgress; //Field offset: 0x2D0
	public static readonly string makeupTools; //Field offset: 0x2D8
	public static readonly string clothingBox; //Field offset: 0x2E0
	public static readonly string suitcaseBox; //Field offset: 0x2E8
	public static readonly string watermelon; //Field offset: 0x2F0
	public static readonly string beachFurniture; //Field offset: 0x2F8
	public static readonly string skatie; //Field offset: 0x300
	public static readonly string foodMixer; //Field offset: 0x308
	public static readonly string casey; //Field offset: 0x310
	public static readonly string tropicalFish; //Field offset: 0x318
	public static readonly string beachToys; //Field offset: 0x320
	public static readonly string poolToys; //Field offset: 0x328
	public static readonly string watermelonPlant; //Field offset: 0x330
	public static readonly string shell; //Field offset: 0x338
	public static readonly string watermelonSeeds; //Field offset: 0x340
	public static readonly string dustRemover; //Field offset: 0x348
	public static readonly string bushNumber; //Field offset: 0x350
	public static readonly string rotaryPhone; //Field offset: 0x358
	public static readonly string boxPallet; //Field offset: 0x360
	public static readonly string cashRegister; //Field offset: 0x368
	public static readonly string woodChipper; //Field offset: 0x370
	public static readonly string gardenBush; //Field offset: 0x378
	public static readonly string gardenStatue; //Field offset: 0x380
	public static readonly string grandfatherClock; //Field offset: 0x388
	public static readonly string ignatius; //Field offset: 0x390
	public static readonly string gardenFurniture; //Field offset: 0x398
	public static readonly string dailyBox; //Field offset: 0x3A0
	public static readonly string rewardBoxCleaning; //Field offset: 0x3A8
	public static readonly string rewardBoxDetergent; //Field offset: 0x3B0
	public static readonly string rewardBoxFlower; //Field offset: 0x3B8
	public static readonly string rewardBoxGardenBench; //Field offset: 0x3C0
	public static readonly string rewardBoxLamp; //Field offset: 0x3C8
	public static readonly string rewardBoxOrangeFlower; //Field offset: 0x3D0
	public static readonly string rewardBoxPaintCan; //Field offset: 0x3D8
	public static readonly string rewardBoxTools; //Field offset: 0x3E0
	public static readonly string ValentineBalloons; //Field offset: 0x3E8
	public static readonly string ValentineCake; //Field offset: 0x3F0
	public static readonly string ValentineBoxOfChocolate; //Field offset: 0x3F8
	public static readonly string ValentineChocolate; //Field offset: 0x400
	public static readonly string ValentineCupidStatue; //Field offset: 0x408
	public static readonly string ValentineGiftPouches; //Field offset: 0x410
	public static readonly string ValentineGiftBoxes; //Field offset: 0x418
	public static readonly string ValentineJewelry; //Field offset: 0x420
	public static readonly string ValentineLoveLetter; //Field offset: 0x428
	public static readonly string ValentineMovieTheaterOpen; //Field offset: 0x430
	public static readonly string ValentineMovieTheaterClosed; //Field offset: 0x438
	public static readonly string ValentineMovieTicket; //Field offset: 0x440
	public static readonly string ValentineRoses; //Field offset: 0x448
	public static readonly string ValentinePlushes; //Field offset: 0x450
	public static readonly string ValentineWeddingInvitation; //Field offset: 0x458
	public static readonly string ValentineDoor; //Field offset: 0x460
	public static readonly string ValentineCurrencyIcon; //Field offset: 0x468
	public static readonly string StPatricksCoal; //Field offset: 0x470
	public static readonly string StPatricksPartyItem; //Field offset: 0x478
	public static readonly string StPatricksFarmEquipment; //Field offset: 0x480
	public static readonly string StPatricksStairCase; //Field offset: 0x488
	public static readonly string StPatricksClover; //Field offset: 0x490
	public static readonly string StPatricksBroth; //Field offset: 0x498
	public static readonly string StPatricksCloverBarrel; //Field offset: 0x4A0
	public static readonly string StPatricksStew; //Field offset: 0x4A8
	public static readonly string StPatricksCastles; //Field offset: 0x4B0
	public static readonly string StPatricksInstruments; //Field offset: 0x4B8
	public static readonly string StPatricksLeprechaunClothing; //Field offset: 0x4C0
	public static readonly string StPatricksJewelry; //Field offset: 0x4C8
	public static readonly string StPatricksOvenEmpty; //Field offset: 0x4D0
	public static readonly string StPatricksLeprechaunToy; //Field offset: 0x4D8
	public static readonly string StPatricksStewPlate; //Field offset: 0x4E0
	public static readonly string StPatricksPotFull; //Field offset: 0x4E8
	public static readonly string StPatricksShepard; //Field offset: 0x4F0
	public static readonly string StPatricksGoldPot; //Field offset: 0x4F8
	public static readonly string StPatricksPotEmpty; //Field offset: 0x500
	public static readonly string StPatricksOvenReady; //Field offset: 0x508
	public static readonly string StPatricksCurrencyIcon; //Field offset: 0x510
	public static readonly string eventRewards; //Field offset: 0x518
	public static readonly string thanksgivingPumpkinPie; //Field offset: 0x520
	public static readonly string doesNotBelong; //Field offset: 0x528
	public static readonly string experience; //Field offset: 0x530
	public static readonly string testingObjectNoVisuals; //Field offset: 0x538

	private static ItemTags() { }

}

