HuntMapActivityDefinition = {
  [ActivityType.HuntMap1] = {
    EntryButtonKey = ESceneViewHudButtonKey.HuntMap1,
    ActivityDataTableName = VirtualDBTableName.icyforestMapExplore,
    ItemDataTableName = VirtualDBTableName.icyforestMapExploreItem,
    ItemLayerDataTableName = VirtualDBTableName.icyforestMapExploreItemLayer,
    ItemCacheDataTableName = VirtualDBTableName.icyforestMapExploreItemCache,
    StateChangedEvent = EEventType.IcyforestMapExploreStateChanged,
    SlotProcessEvent = EEventType.IcyforestMapSlotProcess,
    HuntMapClickBubble = EEventType.HuntMap1ClickBubble,
    HuntMapEndObstacleProcess = EEventType.huntMap1EndObstacleProcess,
    MapExploreClickMainTarget = EEventType.IcyforestMapExploreClickMainTarget,
    HuntMapStartFirstTutorial = EEventType.IcyforestMapExploreStartTutorial,
    MapExploreFinishTutorial = EEventType.IcyforestMapExploreFinishTutorial,
    ConfigKeySuffix = "huntMap1",
    BIClickGuideTask = EBIType.HuntMap1ClickTaskGuidBtn,
    BIClickUnreachableSlot = EBIType.HuntMap1ClickUnreachableSlot,
    BIAcquireObstacleReward = EBIType.HuntMap1ObstacleDisposeReward,
    BIGemBuyToken = EBIType.HuntMap1GemBuyEnergy,
    BIAcquireFreeToken = EBIType.HuntMap1AcquireFreeToken,
    BICostToken = EBIType.HuntMap1CostToken,
    BIAcquireTaskReward = EBIType.HuntMap1TaskReward,
    BIAcquireVipReward = EBIType.HuntMap1VipReward,
    BIAcquireMainTaskReward = EBIType.HuntMap1MainTaskReward,
    BIRewardRecoverBIType = EBIType.HuntMap1RewardRecover,
    BITaskProperty = EBIType.HuntMap1TaskProperty,
    BIEnergyExchange = EBIType.HuntMap1EnergyExchange,
    ActivityTokenPropertyType = EPropertyType.HuntMapEnergyToken,
    TicketPropertyType = EPropertyType.HuntMap1Ticket,
    MapScenePrefabName = ScenePrefabConfigName.HuntMap1MapView,
    MainWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityMainWindow,
    BoardEntryPrefabName = UIPrefabConfigName.HuntMap1ActivityBoardEntry,
    MapEntryPrefabName = UIPrefabConfigName.HuntMap1ActivityMapEntry,
    TaskWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityTaskWindow,
    BoardWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityBoardWindow,
    ReadyWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityReadyWindow,
    EndWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityEndWindow,
    RewardRecoverWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityRewardRecoverWindow,
    HelpWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityHelpWindow,
    ItemBookPrefabName = UIPrefabConfigName.HuntMap1ActivityBookWindow,
    SuccessPrefabName = UIPrefabConfigName.HuntMap1ActivitySuccessWindow,
    MainTaskWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityMainTaskWindow,
    BuyTokenWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityBuyTokenWindow,
    StreakBuyWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityStreakBuyWindow,
    StreakRecoverWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityStreakRecoverWindow,
    StreakMainWindowPrefabName = UIPrefabConfigName.HuntMap1ActivityStreakWindow,
    ActivityTokenIconName = ImageFileConfigName.icon_huntMap_energy,
    EventBookImageName = ImageFileConfigName.huntMap_icon_book,
    MapExploreMainRewardName = ImageFileConfigName.huntmap1_icon_box,
    ResourceLabels = {
      AddressableLabel.HuntMapCommon,
      AddressableLabel.HuntMap1
    },
    TileImageName1 = ImageFileConfigName.huntMap1_tile_bg1,
    TileImageName2 = ImageFileConfigName.huntMap1_tile_bg2,
    PaperBoxSprite = {
      ImageFileConfigName.huntMap1_paperbox
    },
    CobwebSprite = ImageFileConfigName.huntMap1_cobweb,
    TimeLineConfigName = "ExploreTimeLineConfig_huntMap1",
    StoryConfigName = "ExploreStoryConfig_huntMap1",
    BoardOffset = Vector3(-454.6, -378.3, 100),
    BoardScale = 0.916,
    TutorialStartCondition = ETutorialStartCondition.huntMap1Start,
    MainWindowBGM = AudioFileConfigName.SfxHuntmapBgm
  }
}

local function CreateActivityDefinition(activityType, prefix, overrideTable)
  local BaseTable = {
    EntryButtonKey = ESceneViewHudButtonKey[prefix],
    ActivityDataTableName = VirtualDBTableName[prefix .. "Activity"],
    ItemDataTableName = VirtualDBTableName[prefix .. "Item"],
    ItemLayerDataTableName = VirtualDBTableName[prefix .. "ItemLayer"],
    ItemCacheDataTableName = VirtualDBTableName[prefix .. "ItemCache"],
    StateChangedEvent = EEventType[prefix .. "ActivityStateChanged"],
    SlotProcessEvent = EEventType[prefix .. "SlotProcess"],
    HuntMapClickBubble = EEventType[prefix .. "ClickBubble"],
    HuntMapEndObstacleProcess = EEventType[prefix .. "EndObstacleProcess"],
    MapExploreClickMainTarget = EEventType[prefix .. "ClickMainTarget"],
    HuntMapStartFirstTutorial = EEventType[prefix .. "StartTutorial"],
    MapExploreFinishTutorial = EEventType[prefix .. "FinishTutorial"],
    ConfigKeySuffix = activityType,
    BIClickGuideTask = EBIType[prefix .. "ClickTaskGuidBtn"],
    BIClickUnreachableSlot = EBIType[prefix .. "ClickUnreachableSlot"],
    BIAcquireObstacleReward = EBIType[prefix .. "ObstacleDisposeReward"],
    BIGemBuyToken = EBIType[prefix .. "GemBuyEnergy"],
    BIAcquireFreeToken = EBIType[prefix .. "AcquireFreeToken"],
    BICostToken = EBIType[prefix .. "CostToken"],
    BIAcquireTaskReward = EBIType[prefix .. "TaskReward"],
    BIAcquireVipReward = EBIType[prefix .. "VipReward"],
    BIAcquireMainTaskReward = EBIType[prefix .. "MainTaskReward"],
    BIRewardRecoverBIType = EBIType[prefix .. "RewardRecover"],
    BITaskProperty = EBIType[prefix .. "TaskProperty"],
    BIEnergyExchange = EBIType[prefix .. "EnergyExchange"],
    BIDashReward = EBIType[prefix .. "DashReward"],
    ActivityTokenPropertyType = EPropertyType.HuntMapEnergyToken,
    TicketPropertyType = EPropertyType[prefix .. "Ticket"],
    MapScenePrefabName = ScenePrefabConfigName[prefix .. "MapView"],
    MainWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityMainWindow"],
    BoardEntryPrefabName = UIPrefabConfigName[prefix .. "ActivityBoardEntry"],
    MapEntryPrefabName = UIPrefabConfigName[prefix .. "ActivityMapEntry"],
    TaskWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityTaskWindow"],
    BoardWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityBoardWindow"],
    ReadyWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityReadyWindow"],
    EndWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityEndWindow"],
    RewardRecoverWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityRewardRecoverWindow"],
    HelpWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityHelpWindow"],
    ItemBookPrefabName = UIPrefabConfigName[prefix .. "ActivityBookWindow"],
    SuccessPrefabName = UIPrefabConfigName[prefix .. "ActivitySuccessWindow"],
    MainTaskWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityMainTaskWindow"],
    BuyTokenWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityBuyTokenWindow"],
    StreakBuyWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityStreakBuyWindow"],
    StreakMainWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityStreakWindow"],
    DashWindowPrefabName = UIPrefabConfigName[prefix .. "ActivityDashWindow"],
    ActivityTokenIconName = ImageFileConfigName.icon_huntMap_energy,
    DashTokenIconName = ImageFileConfigName[activityType .. "_dash_token"],
    EventBookImageName = ImageFileConfigName.huntMap_icon_book,
    MapExploreMainRewardName = ImageFileConfigName[activityType .. "_icon_box"],
    ResourceLabels = {
      AddressableLabel.HuntMapCommon,
      AddressableLabel[prefix]
    },
    TileImageName1 = ImageFileConfigName[activityType .. "_tile_bg1"],
    TileImageName2 = ImageFileConfigName[activityType .. "_tile_bg2"],
    TimeLineConfigName = "ExploreTimeLineConfig_" .. activityType,
    StoryConfigName = "ExploreStoryConfig_" .. activityType,
    BoardOffset = Vector3(-454.6, -378.3, 100),
    BoardScale = 0.916,
    TutorialStartCondition = ETutorialStartCondition[activityType .. "Start"],
    MainWindowBGM = AudioFileConfigName.SfxHuntmapBgm,
    EnergyNotEnoughColor = UIUtil.ConvertHexColor2CSColor("ce2e2e"),
    EnergyEnoughColor = UIUtil.ConvertHexColor2CSColor("359c24")
  }
  BaseTable.__index = BaseTable
  HuntMapActivityDefinition[activityType] = setmetatable(overrideTable, BaseTable)
  HuntMapActivityDefinition[activityType].__index = HuntMapActivityDefinition[activityType]
end

CreateActivityDefinition(ActivityType.HuntMap2, "HuntMap2", {
  TutorialRoleOffset = Vector3(105, 35, 0),
  CollectAnimDelay = 0.4
})
