namespace MergeEngine.ECS.Systems
{
	public enum SystemPriorities
	{
		InteractionTrackingSystem = 0,
		Hints = 1,
		Scheduling = 2,
		EntityKiller = 3,
		VisualState = 4,
		InviteFriend = 5,
		LiveOpsEvents = 6,
		RemoteLiveOpsEvents = 7,
		InteractionCostSystem = 8,
		BoosterTrigger = 9,
		TimeLimitedPostActivation = 10,
		Expendable = 11,
		Collect = 12,
		Producer = 13,
		Spawner = 14,
		ToolSpawning = 15,
		Chargable = 16,
		TimeLimitedActivation = 17,
		TimeCycle = 18,
		ShopOffer = 19,
		Popup = 20,
		Cards = 21,
		Advertisement = 22,
		BoardIdleHintSystem = 23,
		TimeLock = 24,
		SpecialChainOrders = 25,
		BoardOrderObjectiveHints = 26,
		Orders = 27,
		OrderGenerator = 28,
		Tasks = 29,
		ResourceReplenishment = 30,
		Stats = 31,
		PeriodicSerializer = 32,
		Tips = 33,
		AutoPlay = 34,
		Tutorial = 35,
		BubbledItems = 36,
		RotatingShop = 37,
		ProgressUpdate = 38,
		TimeDuration = 39,
		Time = 40
	}
}
