syntax = "proto2";

package com.common.msg;

import "ItemModuleMsg.proto";

enum TwoMergeModuleMsgSubCommand {
	//获取二合信息
	TWOMERGEMODULEMSG_SUB_TWOMERGEINFO = 30201;
	//同步格子信息
	TWOMERGEMODULEMSG_SUB_SYNGRIDINFO = 30202;
	//使用道具
	TWOMERGEMODULEMSG_SUB_USETWOMERGEITEM = 30203;
	//使用二合里游戏里的道具来升级建筑物废弃掉 直接用建筑升级消息
	//TWOMERGEMODULEMSG_SUB_TWOMERGEBUILDINGLEVELUP = 30204;
	//开仓库格子
	TWOMERGEMODULEMSG_SUB_TWOMERGEOPENGRID = 30205;
	//同步本次二合活动消耗得体力之和
	TWOMERGEMODULEMSG_SUB_TWOMERGECOSTENERGY = 30206;
	//请求交付支线订单(仅针对支线二合订单)
	TWOMERGEMODULEMSG_SUB_TWOMERGESUBMITORDER = 30207;
	//请求商店信息
	TWOMERGEMODULEMSG_SUB_TWOMERGESHOPINFO = 30209;
	//请求购买商店商品
	TWOMERGEMODULEMSG_SUB_TWOMERGESHOPBUYITEM = 30210;
	//请求刷新热卖商品
	TWOMERGEMODULEMSG_SUB_TWOMERGESHOPREFRESHHOTITEM = 30211;
	//请求存储活动二合引导数据
	TWOMERGEMODULEMSG_SUB_TWOMERGEGUIDE = 30212;
	//请求刷新随机订单
	TWOMERGEMODULEMSG_SUB_TWOMERGERANDOMORDER = 30213;
	//更新随机订单结束时间(主要是针对简单订单)
	TWOMERGEMODULEMSG_SUB_TWOMERGERANDOMORDERCD = 30214;
	//请求购买紫体力
	TWOMERGEMODULEMSG_SUB_TWOMERGEBUYPURPLEENERGY = 30215;
}


//获取二合信息请求
message TwoMergeInfoRequest {
	//二合棋盘的id
	optional string cfgId = 1;
}

//生成器对应的itemData数据结构
message ItemGeneratorMsg {
	//历史产出次数
	optional int32 historyCount = 1;
	//当前冷却阶段的产出次数
	optional int32 curCount = 2;
	//冷却结束时间戳
	optional int64 end = 3;
	//停止计时时的时间戳（重新开始计时时 cd结束时间戳为 now +  endTimeStamp-pauseTimeStamp）
	optional int64 pause = 4;
	//当前使用的冷却索引(从0开始)
	optional int32 cdIndex = 5;
}

//宝箱对应的itemData数据结构
message ItemBoxMsg {
	//产出次数
	optional int32 count = 1;
	//开启结束时间戳
	optional int64 end = 2;
	//停止计时时的时间戳（重新开始计时时 cd结束时间戳为 now +  endTimeStamp-pauseTimeStamp）
	optional int64 pause = 3;
}

//气泡状态数据
message ItemStateBubbleMsg {
	//倒计时结束时间戳
	optional int64 end = 1;
}

message GridInfo {
	//格子位置 (目前建议仓库和棋盘中格子通过位置来确定 仓库格子第一个位置从1001001开始  这样棋盘最多有1001001个格子)
	//格子位置编码方式  第一行  从1001开始最多到2000   第二行 从2001开始 最多到3000 以此类推 
	optional int32 position = 1;
	//格子里对应的道具（或其他功能行内容）
	optional string itemId = 2;
	//对应的数量(默认值为1 有些特殊道具有多个数量的情况)
	optional int32 count = 3;
	//根据具体道具来解析成对应的数据结构 目前结构有ItemGeneratorMsg等结构
	optional bytes itemData = 4;
	//格子当前状态(正常 0： 冻结状态1：1 冻结状态2：2 )
	optional int32 state =  5;
	//道具状态 0:正常  1：气泡状态  其他待定义数值
	optional int32 itemState =  6;
	//道具状态数据
	optional bytes itemStateData = 7;
}

message GuideInfo {
	//引导主步骤
	optional int32 mainKey = 1;
	//引导子步骤
	optional int32 subKey = 2;
}

message OrderMsg {
	//订单组id
	optional int32 groupId = 1;
	//上一次完成的订单id(没有为"")
	optional string lastFinishId = 2;
	//订单cd结束时间戳
	optional int64 cdEndTime = 3;
}

message RandomOrderCDInfo {
	//简单订单周期结束时间
	optional int64 simpleEnd = 1;
	//简单订单个数
	optional int32 simpleNum = 2;
	//困难订单cd结束时间
	optional int64 difficultEnd =3;
}

message OrderItem {
	//订单道具id
	optional string itemId = 1;
	//订单道具数量
	optional int32 count = 2;
}

message RandomOrderInfo {
	//随机订单唯一id
	optional string orderId = 1;
	//订单难度等级
	optional int32 difficult= 2;
	//随机需要的道具集合
	repeated OrderItem orderItems = 3;
}

//获取二合信息响应
message TwoMergeInfoResponse {
	//格子信息集合(对于没有同步的格子 客户端可以认为是已解锁的纯空格子)
	repeated GridInfo gridInfos = 1;
	//棋盘中待使用的道具集合(最多同步99个，之后的在使用时如有新的道具在更新)
	repeated string itemIds = 2;
	//仓库额外开的格子数量
	optional int32 extra = 3;
	//二合图鉴中获得得item集合
	repeated string gotItems = 4;
	//已经提交得二合支线订单集合
	repeated string subOrders = 5;
	//二合引导信息
	repeated GuideInfo guideInfos = 6;
	//新增特殊订单消息
	repeated OrderMsg orderMsgs = 7;
	//随机的订单集合
	repeated RandomOrderInfo randomOrderInfos = 8;
	//随机订单CD信息
	optional RandomOrderCDInfo randomOrderCDInfo = 9;
	//已完成固定订单集合
	repeated string fixOrderIds = 10;
	// bp等级
	optional int32 level = 11;
	// bp经验
	optional int32 exp = 12;
	// bp已经领取的基础奖励集合
	repeated int32 baseLevels = 13;
	// bp已经领取的通行证奖励集合
	repeated int32 passLevels = 14;
	// 是否解锁了通行证
	optional bool unlock = 15;
	// 当前紫体力值
	optional int32 purpleEnergy = 16;
	//今日购买紫体力次数
	optional int32 buyPurpleEnergyCount = 17;
}

//同步格子信息请求
message SynGridInfoRequest {
	//二合棋盘的id
	optional string cfgId = 1;
	//同步的格子信息集合(格子信息变化)
	repeated GridInfo gridInfos = 2;
	//有恢复时间点的时间戳复用ItemMsg的cdTimes  count为变化量 正数为增加  负数为减少
	repeated ItemMsg items = 3;
	//获得的新道具集合
	repeated string gotNewItems = 4;
}

//同步格子信息响应
message SynGridInfoResponse {

}

//使用道具请求  道具使用是按照顺序的
message UseTwoMergeItemRequest {
	//二合棋盘的id
	optional string cfgId = 1;
	//对应格子信息
	optional GridInfo gridInfo = 2;
	//使用的二合物品的道具id
	optional string itemId = 3;
}

//使用道具请求响应
message UseTwoMergeItemResponse {
}

////二合建筑升级请求(目前看就是清空对应格子信息就可以)
//message TwoMergeBuildingLevelUpRequest {
//	optional string cfgId = 1;
//	//对应的格子
//	repeated int32 positions = 2;
//	//对应场景id
//	optional string sceneId = 3;
//	//场景中对应的障碍id
//	optional string plantId = 4;
//}

////二合建筑升级请求响应(目前看就是清空对应格子信息就可以)
//message TwoMergeBuildingLevelUpResponse {
	
//}

//开仓库格子
message TwoMergeOpenGridRequest {
	optional string cfgId = 1;
}

//开仓库格子相应
message TwoMergeOpenGridResponse {
}

//同步本次二合活动消耗得体力之和请求
message TwoMergeCostEnergyRequest {
	optional string cfgId = 1;
	optional int32 num = 2;
}

//同步本次二合活动消耗得体力之和响应
message TwoMergeCostEnergyResponse {
	
}

//请求交付支线订单(仅针对支线二合订单) 服务器此处会直接读取对应的奖励直接发放
message TwoMergeSubmitOrderRequest {
	optional string cfgId = 1;
	//配置订单id或自定义随机订单id
	optional string orderId = 2;
	//扣除对应道具后的格子状态(这里不用position来处理的原因就是担心道具有多个 不能直接把格子置空处理，应该是物品数量减1)
	repeated GridInfo gridInfos = 3;
	//使用的二合待使用道具(在待使用列表中删掉对应的道具)
	repeated string waitItems = 4;
	//订单类型 0:策划配置表配置订单(FA第一版)  1:自定义随机订单类型 2:策划配置的固定订单类型(配置表OrderItemSetTemplate)
 	optional int32 orderType = 5;
	//自定义类型订单 同步一下自定义订单的cd结束时间戳 无需同步的情况可以传0
	optional int64 endTime = 6;
}

//请求交付支线订单(仅针对支线二合订单)响应
message TwoMergeSubmitOrderResponse {
	//特殊订单组cd设置为0 (针对于配置订单的返回结果)
	optional int32 groupId = 1;
	//对于自定义随机订单或者OrderItemSetTemplate配置的奖励道具集合
	repeated ItemMsg items = 2;
}

//请求商店信息
message TwoMergeShopInfoRequest {
	optional string cfgId = 1;
}

//商品信息
message ShopItem {
	//位置 从1开始
	optional int32 position = 1;
	//MergeTwoItemTemplate配置表中id
	optional string itemId = 2;
	//已购买次数(看广告或免费领取或者货币购买)
	optional int32 count = 3;
}

//每日商品信息
message DayShopItem {
	//商品信息
	optional ShopItem shopItem  = 1;
	//随机商品的随机索引值 从0开始
	optional int32 randomIndex = 2;
}

//请求商店信息响应
message TwoMergeShopInfoResponse {
	//每日商品集合
	repeated DayShopItem dayShopItems = 1;
	//热卖商品集合
	repeated ShopItem hotShopItems = 2;
	//热卖商品广告每日刷新已用次数
	optional int32 hotAdsCount = 3;
	//热卖商品钻石每日刷新已用次数
	optional int32 hotDiamondCount = 4;
	//上次每日商品刷新时间点
	optional int64 lastDayUpdateTime = 5;
	//上次热卖商品刷新时间点
	optional int64 lastHotUpdateTime = 6;
}

//请求购买商店商品
message TwoMergeShopBuyItemRequest {
	optional string cfgId = 1;
	//商店商品类型 1：每日特价商品 2 : 热卖商品
	optional int32 shopType = 2;
	//商品位置
	optional int32 position = 3;
}

//请求购买商店商品响应
message TwoMergeShopBuyItemResponse {
}

//请求刷新热卖商品
message TwoMergeShopRefreshHotItemRequest {
	optional string cfgId = 1;
	//1: 钻石刷新  2:广告刷新
	optional int32 refreshType = 2;
}

//请求刷新热卖商品响应
message TwoMergeShopRefreshHotItemResponse {
	//热卖商品集合
	repeated ShopItem hotShopItems = 1;
}

//请求存储活动二合引导数据
message TwoMergeGuideRequest {
	//二合棋盘的id
	optional string cfgId = 1;
	//二合引导信息
	optional GuideInfo guideInfo = 2;
}

//请求存储活动二合引导数据响应
message TwoMergeGuideResponse {
	
}

//请求刷新随机订单
message TwoMergeRandomOrderRequest {
	//二合棋盘的id
	optional string cfgId = 1;
	//随机订单信息
	optional RandomOrderInfo orderInfo = 2;
	//cd结束时间戳(不更新时间戳可以不传值)
	optional int64 endTime = 3;
}

//请求刷新随机订单响应
message TwoMergeRandomOrderResponse {
	
}


//更新随机订单结束时间(主要是针对简单订单)
message TwoMergeRandomOrderCDRequest {
	//二合棋盘的id
	optional string cfgId = 1;
	//cd结束时间戳
	optional int64 endTime = 2;
}

//更新随机订单结束时间(主要是针对简单订单)
message TwoMergeRandomOrderCDResponse {
	
}

//请求购买二合紫体力
message TwoMergeBuyPurpleEnergyRequest {
	//体力商店配置id
	optional string purpleShopCfgId = 1;
	//发送扣货币数量(如大于服务器数量 服务器报错， 主要用于校验)
	optional int32 cost = 2;
}
//请求购买二合紫体力响应
message TwoMergeBuyPurpleEnergyResponse {
}